config/routes.rb
Psqlproj::Application.routes.draw do
  resources :homes
  resources :users do
    post :update_photo
  end
  

  root :to => 'homes#index'
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :address, :age, :avatar
  
  has_attached_file :avatar, {:styles => {:small => "50*50>", :thumb => "50*50>"}, :default_url => "/assets/avatar.png"}
  
  validates_attachment_content_type :avatar, :content_type => ['image/jpeg','image/jpg', 'image/png', 'image/gif','image/bmp', 'image/x-png', 'image/pjpeg'] 


# or you can do like this also 
if Rails.env.development?
    has_attached_file :logo,
      :styles => {:thumb => "360x270#", :small=>"50x50#" },
      :path => ":rails_root/public/:attachment/:id/:style/:filename",
      :url => "/:attachment/:id/:style/:filename",
      :default_url => "/assets/logo.png"
 else
    has_attached_file :photo,
      :styles => {:thumb => "360x270#", :small=>"20x20#" },
      :default_url => "http://s3.amazonaws.com/#{ENV['BUCKET_NAME']}/photos/default/:style/missing.png"
  end
  validates_attachment_content_type :logo, :content_type => /\Aimage\/.*\Z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
       @user = User.new
	end	

	def create
       @user = User.new(params[:user])
       if @user.save
         redirect_to users_path
       else
       	 render :action => :new
       end
       
	end	

	def show
      @user = User.find(params[:id])
	end	

  def index
     @users = User.find(:all)
  end	

  def update_photo
     @user = User.find(params[:id])  
     @user.update_attributes(params[:user])
     redirect_to user_path(@user)     
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/index.html.erb
<h1>Homes#index</h1>
<p>Find me in app/views/homes/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Psqlproj" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Psqlproj</a>
          <div class="container-fluid nav-collapse">
            <ul class="nav">
              <li><%= link_to "hotels" %></li>
              <li><%= link_to "Search Hotel" %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span3">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <li class="nav-header">Hotel</li>
              <li><%= link_to "hotels"%></li>
              <li><%= link_to "Add User", new_user_path %></li>
              <li><%= link_to "Users", users_path %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
        <div class="span9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2014</p>
      </footer>
      
    </div> <!-- /container -->

  </body>
</html>

app/views/users/index.html.erb
<h4>index page</h4>


<% @users.each do |user| %>
  <%= user.name %>
  <%= user.address %>
  <%= user.age %>
  <%= link_to "show", user_path(user.id) %>
<% end %>

app/views/users/new.html.erb
<%= form_for @user do |f| %>
 <p>
 Name:	<%= f.text_field :name %>
 </p>

 <p>
 Address:	<%= f.text_field :address %>
 </p>

 <p>
 Age:	<%= f.text_field :age %>
 </p>

 <p>
 Image Upload:	<%= f.file_field :avatar %>
 </p>

 <p>
 	<%= f.submit %>
 </p>

<% end %>

app/views/users/other_logic.html.erb
<h2>Sign up</h2>

<%= form_for(@user, :url => "/admin/users", :method => "POST") do |f| %>
  <div>
    <%= f.label :name %>
    <br />
    <%= f.text_field :name, autofocus: true %>
  </div>

  <div>
    <%= f.label :email %>
    <br />
    <%= f.email_field :email %>
  </div>

  <div>
    <%= f.label :phone %>
    <br />
    <%= f.text_field :phone %>
  </div>

  <div>
    <%= f.label :address %>
    <br />
    <%= f.text_field :address %>
  </div>

  <div>
    <%= f.label :password %>
    <br />
    <%= f.password_field :password, autocomplete: "off" %>
  </div>

  <div>
    <%= f.label :password_confirmation %>
    <br />
    <%= f.password_field :password_confirmation, autocomplete: "off" %>
  </div>

  <div class="form-group">
    <div class="row">
      <div class="col-sm-4">
        <%= f.label :logo %>
        <br />
        <%= f.file_field :logo, :onChange => 'readURL(this)' %>
      </div>

      <div class="col-sm-6">
        <div class="profile_image"> <%= image_tag(@user.logo.url(:original),:style=>"width:150px;height:50px;",:id=>"user_image") %>
        </div>
      </div>
    </div>
  </div>

  <div>
    <%= f.submit "Sign up" %>
  </div>
<% end %>

<script type="text/javascript">
  function readURL(input) {
    if (input.files && input.files[0]) {//Check if input has files.
      var reader = new FileReader();//Initialize FileReader.

      reader.onload = function(e) {
        $('#user_image').attr('src', e.target.result);
        $('#user_image').show();
      };
      reader.readAsDataURL(input.files[0]);
    }
  }
</script>

app/views/users/show.html.erb
<h4>index page</h4>
<div class="row">

</div>
<%= @user.name %>
<%= @user.address %>
<%= @user.age %>

  
  <div class="profile_image"> <%= image_tag(@user.avatar.url(:original),:style=>"width:92px;height:87px;",:id=>"user_image") %>
  </div>



<%= form_for @user, :as => :user, :url => user_update_photo_path(@user, :id => @user.id), :method => "POST", :html => { :multipart => true, :class=>"jqtransform" } do |form| %>
      <%= form.file_field :avatar, :onChange => 'readURL(this)' %>
      <div id="update_image_holder">
        <button type="submit" style="background: none; border: none;">
          <span class="button_left"></span>
          <span class="button_mid">Update</span>
          <span class="button_right"></span>
        </button>
      </div>
    <%end%>

    <script type="text/javascript">
      function readURL(input) {
    if (input.files && input.files[0]) {//Check if input has files.
        var reader = new FileReader();//Initialize FileReader.

        reader.onload = function(e) {
            $('#user_image').attr('src', e.target.result);
            $('#user_image').show();
        };
        reader.readAsDataURL(input.files[0]);
    }
}
    </script>